# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/telehealth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SURaj#123

# JPA / Hibernate Configurations
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf Cache 
spring.thymeleaf.cache=false
server.port=8081
# =========================================================================
# ⚙️ SYSTEM JAVA-MAIL SMTP DISPATCHER CONFIGURATION BLOCK
# =========================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aiicareerapp@gmail.com
spring.mail.password=ccdboamarkgvddvb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true